#php -S localhost:8000
# Obtener todos los libros
GET http://localhost:8000/

###

# Crear un nuevo libro
POST http://localhost:8000/
Content-Type: application/json

{
  "title": "Viento y verdad",
  "author": "Brandon Sanderson",
  "published_year": 2024,
  "genre": "Fantasía"
}

###

# Crear un libro con datos incompletos (falta 'author')
POST http://localhost:8000/
Content-Type: application/json

{
  "title": "El camino de los reyes"
}

###

# Marcar un libro como leído (Actualizar un libro)
PUT http://localhost:8000/
Content-Type: application/json

{
  "id": 1,
  "title": "Viento y verdad",
  "author": "Brandon Sanderson",
  "published_year": 2024,
  "genre": "Fantasía"
}

###

# Eliminar un libro
DELETE http://localhost:8000/
Content-Type: application/json

{
  "id": 1
}